munich-quantum-toolkit/qmap

.github/workflows/ci.yml, .github/workflows/deploy.yml, .gitmodules, CMakeLists.txt, pyproject.toml, setup.py, src/Architecture.cpp, test/CMakeLists.txt, test/test_general.cpp
Up until now, building portable wheels for Apple Silicon did not work properly. This is due to our setup not producing binaries for `arm64`. This PR changes that by allowing to infer the architecture from the environment in `setup.py`.
The external z3 dependency is resolved by downloading the corresponding Apple Silicon bottle from `brew` and installing it manually.
=> Portable wheels for Apple Silicon

.github/workflows/ci.yml, .github/workflows/deploy.yml
This PR updates the Z3 version used in the CI to 4.8.15.
This most certainly fixes the build errors in #38, #39, and #40.
=> 👷 Update Z3

.github/workflows/ci.yml, include/MappingResults.hpp, include/configuration/Configuration.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, src/exact/ExactMapper.cpp, test/test_exact.cpp
This PR adds the option to dump a WCNF file for the instances generated by the exact mapper as exposed by Z3.
Note that it seems that this functionality does not always work as intended from the Z3 side, since the output sometimes stays empty. I assume that this is due to an error being thrown in the library code of Z3 that is caught and not properly propagated. Might be worth to open an issue at their repository.
=> ✨ add option to dump WCNF file from exact mapper

include/configuration/Configuration.hpp, include/utils.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, src/Architecture.cpp, src/exact/ExactMapper.cpp, src/utils.cpp, test/test_exact.cpp
This PR allows mapping to subgraphs of architectures in the exact mapper, which allows to optimally map small circuits to larger architectures.
=> Subgraph mapping

include/Architecture.hpp, src/Architecture.cpp, src/exact/ExactMapper.cpp
This PR significantly reduces the runtime spent in the exact mapper for computing the permutations that need to be considered given a coupling limit by terminating early.
=> ⚡ Early termination in permutation search

include/Mapper.hpp, include/MappingResults.hpp, include/configuration/Configuration.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, src/Mapper.cpp, src/exact/ExactMapper.cpp, src/heuristic/HeuristicMapper.cpp, test/test_exact.cpp, test/test_heuristic.cpp
This PR adds the facilities to conduct pre- and post-mapping optimizations in QMAP.
At the moment, this merely contains a simple post-mapping optimization that tries to cancel adjacent CNOT gates.
Futhermore, this PR adopts the `clone()` functionality provided by the QFR library to clone the circuit upon importing it in the respective mapper in order to avoid side effects of the circuit optimizations conducted inside the mapper.
Finally, this PR slightly changes how gate counts for the resulting circuit are reported. Instead of separately listing the number of single-qubit gates, CNOTs, and SWAPs for the resulting circuit, the results now just list the number of resulting single-qubit and CNOT gates. The number of SWAPs, direction reverses, or teleportations directly resulting from the …
=> ✨ Pre- and Post-Mapping Optimizations

src/exact/ExactMapper.cpp, test/test_exact.cpp
This PR slightly improves the `verbose` output in the exact mapper to make it more useful.
It allows provides a hint to the user, when a WCNF formula could not be obtained by Z3 and how this might be fixed.
Last but not least, it removes a redundant calculation of the architecture coupling limit by slightly refactoring the code.
=> 🚸 Small usability improvements

src/Encodings.cpp, src/exact/ExactMapper.cpp
Logarithm sometimes crashing when max Group size is 1 and var count > 6
Last Group in Commander Grouping not including all elements if the Variable Count is not divisible by Group Size
=> Encoding fixes

README.md, include/configuration/AvailableArchitecture.hpp, src/Encodings.cpp, src/exact/ExactMapper.cpp, test/CMakeLists.txt, test/test_encodings.cpp
This (hopefully) is the last PR that tries to fix the custom atMostOne and exactlyOne encodings. 
TBH, I am really surprised these ever worked.
Fixes #58
=> Fix encodings

.github/workflows/ci.yml, README.md, apps/exact_app.cpp, apps/heuristic_app.cpp, include/Architecture.hpp, include/MappingResults.hpp, include/configuration/Configuration.hpp, mqt/qmap/__init__.py, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, mqt/qmap/qiskit/backend.py, pyproject.toml, setup.py, src/Architecture.cpp, src/Mapper.cpp, test/python/test.py, test/python/test_qiskit_backend_imports.py, test/test_architecture.cpp, test/test_exact.cpp, test/test_heuristic.cpp
This PR brings native support for using Qiskit Backends (e.g., `FakeLondon()`) as architectures in QMAP.
To this end, native translation is provided for all backends implementing either the `BackendV1` or them oder `BackendV2` interface.
In addition to that, QMAP can now als natively read device properties from Qiskit backends, either via the `BackendProperties` class or the modern `Target` class.
In the process, the way device properties and/or calibration data is handled in QMAP has been completely refactored.
This should make it easier to incorporate this information into the available mapping passes in the future.
Solves #12 🥳
=> ✨ Native Support for Qiskit Backends

.readthedocs.yaml, docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/index.rst, docs/source/refs.bib, noxfile.py, setup.py
This PR adds the initial configuration and infrastructure for building proper project documentation on ReadTheDocs.
Building the documentation locally is as easy as
```console
nox -rs docs -- serve
```
> `nox` is best installed via `pipx install nox` (or `brew install nox` if you are on macOS). If you don't have `pipx` (pip for applications) you can install it with `pip install pipx` (or `brew install pipx` if you are on macOS).
At the moment the documentation is pretty much empty. Filling it with content will be done in a separate PR.
=> 📝 Initialize Documentation on ReadTheDocs

.readthedocs.yaml, setup.py
Now that the foundation has been laid in #98, it is time to get things to work properly. 
Of course, the build failed right away because no proper version of Z3 was available for the documentation build.
This PR fixes these build errors by updating the Ubuntu image used to build the docs.
The updated image (Ubuntu-22.04) comes with a recent enough z3 version to build QMAP.
=> 🔧 Fix RtD Documentation Setup

.github/workflows/deploy.yml
This PR adds `fetch-depth: 0` to all checkouts in the deploy workflow.
This is required for `setuptools-scm` to properly infer a proper version number for non-tagged commits (it always infers `mqt.qmap-0.1.dev1` if no commit history with tags is available).
While only a minor improvement, it should allow to catch a few more python packaging errors that might appear in the future.
=> 🔧 Proper Versioning in Deploy CI

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml
Per default, GitHub keeps workflows running even if new commits are added to a pull request.
This is wasteful and requires lots of manual cancellations to free up available runners.
This PR adds the corresponding settings to cancel in-progress jobs whenever new commits become available by adding
```yaml
concurrency:
group: ${{ github.workflow }}-${{ github.ref }}
cancel-in-progress: true
```
snippets to all the workflow files.
=> 🔧 Add in-progress cancellation to CI workflows

.github/codeql-config.yml, .github/workflows/codeql-analysis.yml, include/heuristic/HeuristicMapper.hpp, mqt/qmap/bindings.cpp, src/heuristic/HeuristicMapper.cpp
This PR updates the GitHub CodeQL configuration in anticipation of the deprecation of LGTM.
Most importantly, it adds further checks and a custom build step for C++ to also cover the Python bindings and the tests.
Finally, it also unifies and simplifies the whole configuration again.
By switching to the newer Ubuntu-22.04 runner, a recent enough Z3 version to build QMAP is available by default. This also allows the `codeql-action/init` action to properly build the Python package and (hopefully) provide better analysis.
The additional checks revealed a couple of tiny and easy to fix warnings/alerts that have subsequently been fixed.
=> 🔧 Update CodeQL configuration

.github/workflows/ci.yml, .github/workflows/deploy.yml, pyproject.toml
This PR updates Z3 to its latest version.
Furthermore it tries to pin the actual version of Z3 being used wherever possible. This should ensure better reproducibility across operating systems and the resulting Python packages.
=> ⬆️  Update Z3 from version `4.8.17` to `4.11.2`

include/configuration/Configuration.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, src/Mapper.cpp, test/test_exact.cpp, test/test_heuristic.cpp
This PR adds a new option `add_measurements_to_mapped_circuit` to the QMAP configuration that allows to specify whether measurements should be included in the final circuit or not (defaults to `True`). Using it is as simple as
```python3
from mqt import qmap
qcMapped, result = qmap.compile(qc, arch, add_measurements_to_mapped_circuit=False)
```
Closes #102.
=> ✨ Optionally disable measurements

cmake/FindZ3.cmake
When cross-compiling, the Z3 version cannot be determined by compiling a small code snippet on the host computer.
As a result, no required version for Z3 can be reliably specified.
This PR updates the `FindZ3.cmake` script to determine a proper version also in these cases.
=> 🐛 Fix version check for Z3 when cross compiling

.github/workflows/python-ci.yml, CMakeLists.txt, cmake/FindZ3.cmake, mqt/qmap/compile.py, noxfile.py, pyproject.toml, setup.py, src/Architecture.cpp, test/python/test_compile.py, test/python/test_exact_mapper.py, test/python/test_heuristic_mapper.py, test/python/test_qiskit_backend_imports.py
Currently, Python testing is handled as part of the wheel building process. Every wheel is tested across with all available tests. 
This significantly contributes to the time spent building wheels and is much better left as an individual task.
This PR adds a proper Python testing setup to the CI of the project. To this end, it adds `nox` sessions for determining coverage
```bash 
nox -rs coverage
```
and running the mypy linter
```bash
nox -rs mypy
```
Both of these steps, in combination with the regular tests (`nox -rs tests`), are included in a new CI workflow.
This flow first checks the code base with the mypy linter and then starts running the tests under all supported operating systems and a suitable combination of Python versions. Furthermore, a separate job determines the coverage …
=> 🐍  Python Testing Setup

MANIFEST.in
This tiny PR updates the MANIFEST.in file to reduce the size of the produced source distribution.
=> 📦 Leaner source distribution

.github/codecov.yml
Per default, codecov reports the coverage status on a PR once the first report is uploaded. However, if there is more than one job tracking coverage (C++ and Python, for example), then this incorrectly reports a lowered coverage until both reports have been received.
Conveniently, codecov offers an option to delay the notification so that it only posts the notification after both reports have been received.
=> 🔧 Codecov Config Update

setup.py
The recent update of `retworkx` to version `0.12.0` broke something inside of the Qiskit circuit drawer leading to test failures under Python 3.10. At the moment, there is no tracking issue for that bug and I don't have the time to create one.
This is a temporary workaround that pins `retworkx` to a version less than `0.12.0`.
=> 🐛 temporary workaround for retworkx failure

.github/contributing.rst, .github/support.rst
This tiny PR adds GitHub community health files on `supporting` and `contributing` the QMAP project.
=> :sparkles: Add GitHub community health files

.github/codecov.yml
Up until today it has been a mystery why the coverage report for python was reported as empty on codecov although it was not empty when inspected. No more mystery... turns out codecov was configured to ignore all files under `mqt/**/*`... which effectively turns all coverage reports empty. 
This PR fixes the underlying issue.
In addition, it uses the newly introduced *flag* feature of codecov to split the coverage between the languages.
In the future, different thresholds could be applied to C++ and Python.
=> 🐛🔧 Fix and Enhance Codecov Config

.github/codecov.yml
It turns out that #154 did not properly configure the coverage flags as some header and source files got lost.
This PR tries to fix that and also unifies some of the configuration settings.
=> 🔧 Fixup codecov flag config

mqt/qmap/compile.py, setup.py
This PR fixes an issue caused by a breaking change in the newest `qiskit-terra` update. The `_layout` member of `QuantumCircuit`s has been changed to a data class. This caused our circuit import and also the export to fail on the newer version.
This has not been caught earlier because QCEC (which is a test dependency) still capped qiskit-terra at `<0.22`.
In addition to the fix above, this PR loosens many of the dependency versions in order to avoid such situations in the future.
=> 🐛 Fix Qiskit compatibility

CMakeLists.txt, README.md, cmake/FindZ3.cmake, docs/source/DevelopmentGuide.rst, docs/source/Installation.rst, src/Architecture.cpp
- Bumped the minimum required version of CMAKE to 3.19 (to enable the use of `find_package_check_version`)
- Fixed issue in CMAKE when z3 python root path is empty
- replaced `std::regex_match` with `std::regex_search` in the loading of coupling maps for a more lenient handling of white spaces in coupling map files
=> Fix compile issues

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/deploy.yml, .github/workflows/python-ci.yml
This PR makes sure that CI jobs are not cancelled on the `main` branch, but only on pull requests.
This should avoid incomplete coverage data collection and ensure that every commit to the main branch passes CI.
=> 🔧 Only cancel repeated CI jobs for Pull Requests

include/Architecture.hpp, include/Mapper.hpp, include/MappingResults.hpp, include/configuration/AvailableArchitecture.hpp, include/configuration/CommanderGrouping.hpp, include/configuration/Configuration.hpp, include/configuration/Encoding.hpp, include/configuration/InitialLayout.hpp, include/configuration/Layering.hpp, include/configuration/Method.hpp, include/configuration/SwapReduction.hpp, include/exact/ExactMapper.hpp, include/heuristic/HeuristicMapper.hpp, include/heuristic/unique_priority_queue.hpp, include/utils.hpp
The use of [`#pragma once`](https://en.wikipedia.org/wiki/Pragma_once) in favor of include guards comes with several advantages, including: less code, avoidance of name clashes, and sometimes improvement in compilation speed.
=> ♻️ consistently use `#pragma once`

include/Architecture.hpp, include/utils.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, mqt/qmap/load_architecture.py, mqt/qmap/load_calibration.py, src/Architecture.cpp, src/utils.cpp, test/test_architecture.cpp
This PR cherry picks changes from #78 that are not related to Clifford synthesis. 
Since it has been over 4 months since the creation of #78, quite some changes are lying around there.
This should also make reviewing of the other PR easier, since the changes here have already been reviewed.
Most of the changes make sure that fixed-width integer types are used throughout the architecture class.
In addition, some further linter warnings have been fixed in anticipation of #105.
Last but not least, some convenience functions for loading quantum circuits, architectures, and calibration data have been extracted.
=> ♻️ Extract Clifford Synthesis-independent Changes from #78

.github/workflows/deploy.yml
The recent GitHub runner update to Ubuntu 22.04 broke the sdist CI job. This PR fixes the job so that #210 should also be able to complete successfully.
=> 🐛 Fix broken sdist CI (caused by switch to Ubuntu 22.04)

.flake8
`flake8-bugbear` recently introduced the following opinionated warning:
> B905: zip() without an explicit strict= parameter set. strict=True causes the resulting iterator to raise a ValueError if the arguments are exhausted at differing lengths. The strict= argument was added in Python 3.10, so don't enable this flag for code that should work on <3.10. For more information: https://peps.python.org/pep-0618/
As stated, this only applies to Python 3.10+ and cannot be resolved for older Python versions. As a consequence, we disable that check for the foreseeable future.
=> 🚨🐛 Disable opinionated bugbear warning

.readthedocs.yaml, pyproject.toml
This PR gets rid of the Z3 build dependency. Due to build isolation, the virtual environment containing Z3 (that is being linked to the C++ binding library) does no longer exist after the build. Hence, the package install is essentially broken if the Z3 Python package is picked up during the build.
This was a workaround for getting the RtD build to work. I managed to work around the underlying issue by figuring out a way to specify the `Z3_ROOT` environment variable for the package installation step.
=> 🔥 Remove Z3 from build dependencies

.github/workflows/deploy.yml
Due to a misconfiguration in the CI, x86 wheels for macOS were no longer being built. This PR fixes the underlying issue. Thanks @hillmich for noticing!
=> 🐛 fix missing macOS x86 wheels

include/configuration/Configuration.hpp, include/heuristic/HeuristicMapper.hpp, mqt/qmap/bindings.cpp, mqt/qmap/pyqmap.pyi, src/heuristic/HeuristicMapper.cpp
- isolated the heuristic to HeuristicMapper::Node::updateHeuristicCost for less redundant code and easier expansion with further heuristic types (e.g. the planned fidelity aware approach)
- removed redundant field HeuristicMapper::Node::totalCost (redundant to HeuristicMapper::Node::costFixed)
- added consider_fidelity field to configuration classes
=> ✨Heuristic mapper fidelity preparation

src/Architecture.cpp, test/test_architecture.cpp
For whatever reason, the computation of the coupling limit of an architecture is broken since its introduction.
It remains unclear, why this was not detected earlier, but definitely shows the lack of tests for that feature.
=> 🐛 Fix Coupling Limit Computation

src/exact/ExactMapper.cpp, test/test_exact.cpp
Recent experiments have identified an error in the circuit extraction procedure of the exact mapper when the mapped circuit uses more qubits than the original circuit.
This PR resolves the errors by properly handling these cases.
=> 🐛 Fix Circuit Extraction in Exact Mapper

.github/workflows/python-ci.yml, .pre-commit-config.yaml, noxfile.py, pyproject.toml
Qiskit(-terra) is bound to drop Python 3.7 support in the upcoming `0.25.0` update and a warning is issued since the newly released `0.23.0`. 
To avoid any future disruptions, Python 3.7 support is dropped with this PR.
=> 🐍🔥 Drop Python 3.7 support

src/exact/ExactMapper.cpp
It turns out that the limitation on the number of variables in the exact mapper is no longer required since the introduction of the LogicBlocks submodule as it does not use Z3's `expr_vector` directly. 
This should allow to map circuits with more gates (and maybe even more qubits in some cases) than before.
@pehamTom might be interesting to you since you hit that limitation a couple days back.
=> 🔥 Drop variable limitation for exact mapper

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/cpp-linter.yml, .github/workflows/deploy.yml, .github/workflows/python-ci.yml
This tiny PR adds the `merge_group` label to the GitHub workflows in order to make them work with merge queues.
=> 🔧 add `merge_group` to workflow configs

.github/workflows/python-ci.yml, .pre-commit-config.yaml, noxfile.py, pyproject.toml
I recently found out that you can explicitly exclude pre-commit checks from the CI bot, so that they are never really initialised. This allows to incorporate `mqt.qcec` (and in turn `qiskit-terra`) to be included in the type checking; previously this exceeded the memory capacity of the pre-commit.ci service.
With this change, `mypy` is also included in the default pre-commit checks when run locally. Expect a slight runtime increase the first time trying to run pre-commit or its git hooks after this change as mypy build sup its cache.
=> 🔧 mypy configuration update

src/Mapper.cpp, test/test_heuristic.cpp
In the process of creating layers using the disjoint qubit strategy, multiple gates acting on the same qubit ended up in the same layer. As a result the heuristic mapping process ended up in an infinite looping searching for a possible mapping.
Problem:
When the previous gate was appended to a existing layer, the **lastLayer** variable was not updated correctly.
Fixes # (issue)
- fixed creation of disjoint layers
=> Fix disjoint layer

include/cliffordsynthesis/Configuration.hpp, mqt/qmap/bindings.cpp, mqt/qmap/pyqmap.pyi, src/cliffordsynthesis/CliffordSynthesizer.cpp, test/cliffordsynthesis/test_synthesis.cpp
This PR adds an option to dump the intermediate results during Clifford synthesis.
The way it works is that, if the `dump_intermediate_results` option is set to `true`, a QASM file is dumped for every successfully synthesized circuit into the path specified by the `intermediate_results_path` setting (defaults to `./`; the current working directory).
This should allow to work with intermediate synthesis results in cases where the SAT solver just takes to long to determine the optimal result.
=> 🔊 Allow to dump intermediate synthesis results

include/utils.hpp, src/utils.cpp
The Dijkstra implementation in `utils.hpp` currently uses a priority queue of pointers, which therefore does a comparison of the pointers themselves instead of calling the < operator for the nodes when determining node order.
This is fixed in this pull request via a node comparator and initializing the priority queue with that.
=> Dijkstra node order bug fix

src/Mapper.cpp
Currently, the layering strategy `DisjointQubits` always inserts gates in the last layer. By instead inserting it one layer after the first layer (from the back of the circuit), in which it would intersect with the qubit set of a previous gate, we achieve a still valid layering with less layers. Visually speaking, we move each gate as far left as possible without intersecting other gates.
The following visualizations illustrate the status-quo and the new solution proposed in this PR on the following circuit:
The numbers next to the gates indicate the gate order in the circuit.
Currently, the following layering strategy is implemented (red dots indicate the state of `laystLayer` for each qubit after inserting the gate):
The proposed implementation:
=> fix disjoint qubit layering

include/heuristic/HeuristicMapper.hpp
Fixing a small bug in the node ordering of A* search, in which the heuristic cost is only considered for nodes with different fixed cost + lookahead penalty
=> Fix A* node ordering

src/exact/ExactMapper.cpp, test/test_exact.cpp
Fixes #251.
For some reason the cost contribution of direction reverses in the exact mapper was inverted, i.e., the mapper effectively considered direction reverses to be "free". This PR fixes the underlying condition and adds a corresponding regression test.
=> 🐛  Fix cost contribution of direction reverse in exact mapper

src/cliffordsynthesis/Tableau.cpp, test/test_tableau.cpp
In `applyCX` in the Tableau class the control and target qubits were incorrectly applied.
=> 🐛 Fixed bug in Clifford circuit tableau simulation

include/Architecture.hpp, include/configuration/Configuration.hpp, src/Architecture.cpp, src/exact/ExactMapper.cpp, test/test_exact.cpp
Fixes #256.
The underlying cause of the performance regression was an oversight in the addition of the SWAP limitation feature for the ASPDAC 2021 paper. The implementation did not properly handle directed architectures in various cases:
- due to the unidirectional edges, the longest shortest path search would sometimes return paths that were too long. That alone wouldn't be a problem, but makes the performance suboptimal. This is fixed by making sure that the search for the longest shortest path considers edges in the coupling graph as bidirectional.
- More critically, the coupling limit computation only computes the cost of moving any two qubits next to each other. However, in directed architectures, this might not be enough to make a two-qubit gate executable. The simplest case, where …
=> 🐛 Fix performance regression in exact mapper on directed architectures

.github/workflows/deploy.yml
https://github.com/pypa/gh-action-pypi-publish changed the naming convention for action parameters from snake_case to kebab-case. While the old syntax will be supported until the next major version increase, a warning is admitted as of the latest version.
This PR changes the `skip_existing` option to `skip-existing` to reflect the above change and silence the warning.
=> 🩹 change PyPI upload option to kebab-case

.pre-commit-config.yaml, mqt/qmap/subarchitectures.py, pyproject.toml, setup.py, test/python/test_compile.py, test/python/test_exact_mapper.py, test/python/test_heuristic_mapper.py, test/python/test_qiskit_backend_imports.py
This small PR updates the configuration of the ruff pre-commit hook. Since `v0.255`, the `target-version` configuration property can be inferred directly, which allows to simplify the configuration.
It also fixes some newly introduced warnings.
=> ⬆️🪝 Update ruff and use automatic `target-version` inference

include/Architecture.hpp, include/utils.hpp, src/Architecture.cpp, src/utils.cpp, test/test_general.cpp
Replacing fixed edge costs in Dijkstra implementation with an edge weight matrix. Thereby enabling future expansions (fidelity-aware distances, semi-directional architectures, etc.)
=> Dijkstra arbitrary weights

include/heuristic/HeuristicMapper.hpp, src/heuristic/HeuristicMapper.cpp, test/test_heuristic.cpp
- Replacing iterations over all gates in the heuristic with iterations over a collection counting gate multiplicities (i.e. the number of gates acting on each logical qubit)
- Moving large methods in `HeuristicMapper::Node` from hpp to cpp
- Moving all cost computations inside `HeuristicMapper::Node` methods, and only interacting with nodes via method calls
=> ♻️ Refactor heuristic mapper

test/test_heuristic.cpp
Implements a new test performing depth-limited depth first search on a small mapping problem using `HeuristicMapper::Node` and checking heuristic costs on each solution search path for admissibility.
=> Test heuristic for admissibility

docs/source/library/MappingResults.rst, include/MappingResults.hpp, include/configuration/Configuration.hpp, include/heuristic/HeuristicMapper.hpp, mqt/qmap/bindings.cpp, mqt/qmap/compile.py, mqt/qmap/pyqmap.pyi, src/configuration/Configuration.cpp, src/heuristic/HeuristicMapper.cpp, test/test_heuristic.cpp
Implements some benchmarks into the heuristic mapper (both for the whole mapping process, and for each layer):
- number of generated nodes
- number of expanded nodes
- depth of the retrieved solution in the search tree (only for each layer, not globally for the whole mapping process)
- average branching factor (i.e. how many children does a node generate on average)
- effective branching factor (i.e. how many of those children on average were expanded before the solution was found; or in other words the branching factor, which a balanced, uniform tree would need to have, to contain the number of processed nodes (expanded + 1) with a depth equal to the solution depth)
- the average time spent on each expanded node
All of this will help keeping track of performance changes, when …
=> Heuristic Benchmarking

include/cliffordsynthesis/Configuration.hpp, include/cliffordsynthesis/encoding/SATEncoder.hpp, mqt/qmap/bindings.cpp, src/cliffordsynthesis/CliffordSynthesizer.cpp, test/cliffordsynthesis/test_synthesis.cpp
This PR adds a setting to the config that allows to set the lower limit for the binary search.
Sometimes a lower bound for the circuit might already be known and one can save on some calls to the Solver by limiting the search space during binary search.
=> 🚸 Allow for setting minimal timesteps for binary search.

src/configuration/Configuration.cpp
Moving `admissible_heuristic` and `consider_fidelity` in the JSON representation of `Configuration` from `config.settings.lookahead` to `config.settings`.
=> Move `admissible_heuristic` and `consider_fidelity` in JSON of `Configuration`

include/Architecture.hpp, include/utils.hpp, src/Architecture.cpp, src/heuristic/HeuristicMapper.cpp, src/utils.cpp, test/test_general.cpp
The current heuristic implementation, when determining if a reversal will be necessary for some given CNOT on a unidirectional architecture, considers only the 2 edges next to the 2 qubits involved in the CNOT along the shortest path (i.e. it assumes that one of the 2 qubits will eventually move all the way next to current position of the other qubit, instead of possibly meeting somewhere in the middle). However, if there is _any_ edge along the shortest path, a reversal might in fact not be necessary. Thereby, the current implementation overestimates the true cost (i.e. violates admissibility) in some cases.
This PR fixes this by only applying the reversal cost if no edge along the shortest path is oriented in the right direction.
Additionally, a minor bug fix in benchmarking: The checks …
=> Fix cnot reversal in heuristic

include/cliffordsynthesis/CliffordSynthesizer.hpp, pyproject.toml, src/cliffordsynthesis/CliffordSynthesizer.cpp, test/python/test_cliffordsynthesis.py
Remove redundant gates in post-processing step after depth-optimal synthesis
Fixes #325
=> Remove redundant gates after depth-optimal synthesis.

pyproject.toml
Fixes CI. The newest Qiskit version introduced a new deprecation warning for some version attribute and, for some reason, that warning trips up pytest without our code actually using the deprecated attribute.Fixes # (issue)
=> patch CI failure due to unconditional Qiskit deprecation warning

pyproject.toml
The newest Qiskit release introduced some new deprecations and, unfortunately, also some internal deprecation warnings that now surface in our tests and must be ignored.
This PR adjusts MQT QMAP to these latest changes.
=> 🚨 Adapt to latest Qiskit version

include/Mapper.hpp, include/configuration/Configuration.hpp, src/Mapper.cpp, src/heuristic/HeuristicMapper.cpp, src/mqt/qmap/compile.py, src/mqt/qmap/pyqmap.pyi, src/python/bindings.cpp, test/test_heuristic.cpp
This PR fixes a minor bug in `disjoint_2q_block` Layering, where it previously pushed 2q-gates erroneously to the second layer, if the first layer has 1q-gates already applied to the same qubits. 
I also took this as an opportunity to separate `disjoint_2q_block` and `disjoint_qubits` into 2 different functions for the sake of readability. It was already getting cluttered now, and with a soon-to-come suggestion for another similar layering technique (specifically designed for noise-aware mapping) the problem will probably only get worse. 
In my opinion, the ensuing code duplication is not too bad, but if you disagree, I am also happy to reintegrate both functions back into one.
Additionally, I added the mapping option `add_barriers_between_layers` intended for making layer boundaries …
=> Fixing minor bug in `disjoint_2q_block` Layering and adding option `add_barriers_between_layers`

src/heuristic/HeuristicMapper.cpp, test/test_heuristic.cpp
The changed line previously treated `qc::QuantumComputation::initialLayout` as a mapping from virtual qubits to physical qubits instead of the other way around, which seems to be the canonical way everywhere else in the project. This leads to invalid qubit layouts in some edge cases (i.e. non-bijective mappings)
=> Fixing bug in single-qubit gate adjusting in `HeuristicMapper`

src/heuristic/HeuristicMapper.cpp, test/test_heuristic.cpp
Fixing a minor bug, where sometimes the number of generated nodes is undercounted in the benchmark because nodes with equivalent layout are not added multiple times to the priority queue. Therefore, instead of relying on the size of the priority queue, it is more stable to rely on the node ids, which are strictly incremented for each generated node.
=> Fix `generatedNodes` benchmark bug

src/mqt/qmap/visualization/visualize_search_graph.py
Fixing a bug, where in some cases passing `show_layout=None` to `SearchVisualizer` (i.e. hiding the architecture/layout graph), will call the architecture visualization procedure without valid architecture node positions resulting in an exception being raised.
=> Fixing bug with `show_layout=None` in `SearchVisualizer`

src/mqt/qmap/visualization/search_visualizer.py, src/mqt/qmap/visualization/visualize_search_graph.py
- Adding a new option to the search graph visualizer to only show the final solution path in each layer (intended for large, convoluted search trees and situations where only the final solution is of interest)
- Fixing a minor bug that rendered the option `tapered_search_layer_heights` ineffective in many cases
=> SearchVisualizer: New feature `show_only_solution_path` and fixing `tapered_search_layer_heights`

.pre-commit-config.yaml, CMakeLists.txt, cmake/ExternalDependencies.cmake, cmake/cmake_uninstall.cmake.in, include/DataLogger.hpp, include/Mapper.hpp, include/cliffordsynthesis/CliffordSynthesizer.hpp, include/cliffordsynthesis/Results.hpp, noxfile.py, pyproject.toml, src/CMakeLists.txt, src/DataLogger.cpp, src/cliffordsynthesis/Tableau.cpp, src/mqt/qmap/clifford_synthesis.py, src/mqt/qmap/compile.py, src/mqt/qmap/pyqmap.pyi, src/mqt/qmap/subarchitectures.py, src/python/CMakeLists.txt, src/python/bindings.cpp, test/CMakeLists.txt, test/cliffordsynthesis/test_synthesis.cpp, test/python/constraints.txt, test/python/test_subarchitectures.py, test/test_exact.cpp, test/test_heuristic.cpp
This PR updates the mqt-core submodule and brings in some further advancements from #418.
Specifically, it switches to using `FetchContent` for obtaining `mqt-core` (and `LogicBlocks`).
Per default, it is pointed to the vendored submodule via an overridable CMake variable.
=> ⬆️ update mqt-core

pyproject.toml, src/mqt/qmap/load_calibration.py, src/mqt/qmap/qiskit/backend.py, src/mqt/qmap/subarchitectures.py, test/python/constraints.txt, test/python/test_cliffordsynthesis.py, test/python/test_exact_mapper.py, test/python/test_heuristic_mapper.py, test/python/test_qiskit_backend_imports.py, test/python/test_subarchitectures.py
This PR updates the project to work with the latest Qiskit version. In turn, and in preparation for the 1.0 release of Qiskit, it adapts the project to the expected removals already. While this raises the minimum supported Qiskit version to 0.46.0, it should make switching to 1.0 as easy as possible.
=> 🚨 adapt for Qiskit 0.46.0

test/CMakeLists.txt
This fixes a small mistake in the CMake configuration that would prevent the usage of mqt-qmap as a submodule.
=> 🩹 fix test file configuration

pyproject.toml, src/mqt/qmap/load_calibration.py, src/mqt/qmap/qiskit/backend.py, src/python/CMakeLists.txt, test/python/constraints.txt, test/python/test.py, test/python/test_qiskit_backend_imports.py
This PR marks the official support of Qiskit 1.0 in mqt-qmap.
In order to avoid all kinds of ugly compatibility hacks, this PR also changes the minimum required Qiskit version to 1.0.
Since Qiskit has devoted themselves to following semantic versioning from now on out, this hopefully means fewer compatibility changes in the future.
=> ✨ Support for Qiskit 1.0

docs/source/Mapping.ipynb, src/mqt/qmap/__init__.py, test/python/test_compile.py
The recently triggered CD run (https://github.com/cda-tum/mqt-qmap/actions/runs/7991506462/job/21822820046) has revealed that the search space visualisation feature of the heuristic mapper was never truly optional.
This is caught now because Qiskit has dropped the `networkx` dependency completely in favour of `rustworkx`, which makes the CD pipeline fail.
This PR fixes this complication and makes the visualisation extra truly optional.
=> 🚸 truly make search space visualization optional

.pre-commit-config.yaml
This PR updates the jupyter notebook cleaning pre-commit check to preserve MIME metadata. This allows to use raw RST cells within jupyter notebooks, which can be very helpful for using Sphinx references as part of the documentation.
=> 🚸 allow using raw RST cells in jupyter notebooks

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
This PR switches the reusable workflows from MQT Core to the ones hosted at https://github.com/cda-tum/mqt-workflows. This creates a better separation of concerns and allows for separate versioning of the workflows and the MQT Core library.
Furthermore, this PR adapts the configuration of the continuous deployment job so that the job is also triggered if the respective workflow file is updated. This should help to catch errors as early as possible when dependabot updates the workflow.
=> 🧱 switch to dedicated reusable MQT workflows

src/python/bindings.cpp, test/python/test_hybridmap.py
This fixed the problem that for the Hybridmapper, using the Python bindings it can happen that the architecture object is deleted by the garbage collector, loosing the reference for the mapper. Now it is kept alive using the keep_alive functionality of PyBind.
=> Keep na arch alive 2

.github/workflows/cd.yml, .github/workflows/ci.yml, pyproject.toml
This PR makes use of `cibuildwheel`'s latest addition of a `build[uv]` build frontend option that uses `uv` under the hood to speed up the build process.
Furthermore, it adjusts the Windows repair command to respect namespace packages.
=> ⚡🔧 Faster cibuildwheel and better Windows wheel repair

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/update-mqt-core.yml
This PR updates the mqt-workflows to their latest version. The only real change is that the MQT Core update workflow now requires a token.
For the moment, the token being used is the regular GitHub token, which means that the resulting PRs won't automatically trigger CI runs.
=> ⬆️ update mqt-workflows to 1.1.1

.github/workflows/cd.yml, .pre-commit-config.yaml, src/mqt/qmap/subarchitectures.py
This PR enables artifact attestations for the sdist and wheels produced via the continous deployment job.
This allows users to verify that the artifacts were built using our GitHub Action.
=> 📦 add artifact attestation

.github/workflows/cd.yml, .github/workflows/ci.yml, cmake/ExternalDependencies.cmake, noxfile.py, pyproject.toml, src/python/bindings.cpp
The (ABI-stable) release candidate for Python 3.13 just released and the newest MQT Workflows include an updated version of cibuildwheel that supports building wheels for it.
This PR enables regular Python 3.13 builds and also enables builds for the new free-threaded variant.
=> ✨ Python 3.13 Support

.pre-commit-config.yaml, include/Architecture.hpp, include/na/NAGraphAlgorithms.hpp, include/utils.hpp, pyproject.toml, src/Architecture.cpp, src/mqt/qmap/subarchitectures.py, src/na/NAGraphAlgorithms.cpp, src/utils.cpp, test/hybridmap/test_hybridmap.cpp, test/na/test_architecture.cpp, test/test_exact.cpp, test/test_general.cpp, test/test_heuristic.cpp
This PR adds schema validation to the pre-commit hooks. In addition, it also replaces codespell with `crates-ci/typos` and fix all newly brought up typos.
Finally, the PR runs `pre-commit autoupdate`.
=> ⬆️🪝 update pre-commit config

.github/workflows/cd.yml, .github/workflows/ci.yml, .github/workflows/update-mqt-core.yml, pyproject.toml
This PR updates the MQT workflows to `v1.3`, which is the first version to offer moving minor tags that should reduce the update frequency.
Furthermore, the updated workflows combine the emulated wheel jobs to reduce overall build time and reduce the number of parallel jobs.
=> ⬆️ update mqt-workflows to v1.3 (moving tag)

cmake/ExternalDependencies.cmake, noxfile.py, pyproject.toml
This small PR updates the requirement on pybind11 to `2.13.5` which contains a fix for some relative paths that could trip up compilers.
=> ⬆️ require pybind11 >= 2.13.5

.github/workflows/cd.yml, pyproject.toml
CentOS 7, which the default `manylinux2014` image is based on, reached end-of-life in June 2024.
The only meaningful platforms left that do not provide a recent enough `glibc` version are some `Amazon Linux 2` platforms, which are not really relevant for the MQT.
This PR moves the Linux wheel builds to the more recent `manylinux_2_28` images, which offers many performance improvements and optimizations.
=> 🐍⬆️ update image for Linux wheel builds to manylinux_2_28

test/sc/heuristic/test_heuristic.cpp
Due to some unknown reason, the test suite suddenly started to fail on linux systems for one particular heuristic mapper test.
The underlying issue seems to have been some concurrency issue in combination with the logging functionality in the heuristic mapper.
The fix for now was to add a random suffix to the data logger path for all respective tests.
=> 🐛 Fix test suite regression in heuristic mapper

.github/renovate.json5, .pre-commit-config.yaml, noxfile.py, pyproject.toml, src/mqt/qmap/subarchitectures.py, uv.lock
This pull request introduces the following changes:
- Enabled automerge for minor version updates of stable dependencies and lockfile update PRs to streamline dependency management.
- Updated the lockfile to reflect the latest dependency resolutions.
- Upgraded the Sphinx dependency for documentation to ensure compatibility.
- Adopted PEP 639 license expressions for uniformity and compliance.
- Updated to `scikit-build-core` version 0.11 for improved build performance and new features.
- Enabled verbose logging for install commands to aid in debugging and transparency.
- Updated the pre-commit checks and applied the corresponding suggestions.
=> ⬆️ scikit-build-core 0.11, PEP 639 license expressions, sphinx fixes, more automerge

CHANGELOG.md, src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp, test/na/zoned/test_compiler.cpp
At the moment when atoms are moved back from the entanglement zone to the storage zone, the nearest site is used as a reference. However, when no site was free in the column of the nearest site, then a lookup in the map of discretized column indices would lead to a segmentation fault. This is fixed now. If the case described before happens, the column closest to the column of the nearest site is taken.
Fixes #727
=> 🐛 Fix Lookup of Discrete Columns in routing-aware Compiler
