munich-quantum-toolkit/qmap

README.md
apps/heuristic_app.cpp
include/Architecture.hpp
include/MappingResults.hpp
include/MappingSettings.hpp
include/heuristic/HeuristicMapper.hpp
jkq/qmap/bindings.cpp
src/Mapper.cpp
src/heuristic/HeuristicMapper.cpp
test/test_heuristic.cpp

The previous code was not ported correctly. Fixes #7
The ancilla selection was wrong and so was the case where not suitable edge was found in `mapUnmappedGates`.

Fix for teleportation

---

README.md
include/configuration/AvailableArchitecture.hpp
mqt/qmap/bindings.cpp
test/test_exact.cpp

Adds Rigetti architectures Agave and Aspen

add rigetti agave and aspen

---

setup.py

The recent major update of setuptools (version 64) broke our editable install workflow.
This PR makes editable installs work properly again.

🐛 Fix Editable Installations

---

.flake8
.pre-commit-config.yaml
mqt/qmap/__init__.py
mqt/qmap/compile.py
setup.py
test/python/test_compile.py

This PR adds a couple more convenient flake8 checks that ensure "modern" Python is used throughout the project.
This might especially become important if pure Python contributions like #106 become more.

🚨 Further flake8 checks

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md

This PR adds issue and pull request templates to the project in a similar fashion as in https:github.com/cda-tum/qcec.

✨ Add issue and pull request templates

---

include/Architecture.hpp
include/Mapper.hpp
include/MappingResults.hpp
include/configuration/AvailableArchitecture.hpp
include/configuration/CommanderGrouping.hpp
include/configuration/Configuration.hpp
include/configuration/Encoding.hpp
include/configuration/InitialLayout.hpp
include/configuration/Layering.hpp
include/configuration/Method.hpp
include/configuration/SwapReduction.hpp
include/exact/ExactMapper.hpp
include/heuristic/HeuristicMapper.hpp
include/heuristic/unique_priority_queue.hpp
include/utils.hpp
mqt/qmap/bindings.cpp
src/Architecture.cpp
src/Mapper.cpp
src/exact/ExactMapper.cpp
src/heuristic/HeuristicMapper.cpp
src/utils.cpp
test/test_architecture.cpp
test/test_encodings.cpp
test/test_exact.cpp
test/test_general.cpp
test/test_heuristic.cpp

This PR reworks the C++ file headers so that they neatly fit into two lines and makes sure that every C++ file has such a header.

✏️ Consistent file headers

---

.pre-commit-config.yaml
CMakeLists.txt
include/cliffordsynthesis/Tableau.hpp
src/CMakeLists.txt
src/cliffordsynthesis/Tableau.cpp
test/CMakeLists.txt
test/test_tableau.cpp

This PR extracts the Stabilizer tableau functionality from #78.
To this end, it introduces a class for representing, reading, and writing these Tableaus.
Furthermore, it adds the functionality to create the Stabilizer Tableau for a  quantum circuit.
More tests asserting the functionality to come.

✨ Stabilizer Tableaus

---

.github/workflows/codeql-analysis.yml
include/Mapper.hpp
include/cliffordsynthesis/CliffordSynthesizer.hpp
mqt/qmap/bindings.cpp
src/Mapper.cpp
src/cliffordsynthesis/encoding/GateEncoder.cpp
src/exact/ExactMapper.cpp
src/heuristic/HeuristicMapper.cpp
test/cliffordsynthesis/test_synthesis.cpp
test/test_architecture.cpp
test/test_encodings.cpp
test/test_exact.cpp
test/test_heuristic.cpp
test/test_tableau.cpp

This PR ensures that QCEC also works with the latest QFR version. The latest update (https://github.com/cda-tum/qfr/pull/244) caused some breaking changes which need to be accounted for here.
All of the changes are minor and should not have any performance impact.

🚑 Fixup for newest QFR version

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cpp-linter.yml
.gitmodules
CMakeLists.txt
include/Architecture.hpp
include/Mapper.hpp
include/cliffordsynthesis/CliffordSynthesizer.hpp
include/cliffordsynthesis/Tableau.hpp
include/cliffordsynthesis/encoding/GateEncoder.hpp
include/cliffordsynthesis/encoding/ObjectiveEncoder.hpp
include/cliffordsynthesis/encoding/SATEncoder.hpp
include/cliffordsynthesis/encoding/TableauEncoder.hpp
include/configuration/CommanderGrouping.hpp
include/configuration/Encoding.hpp
include/utils.hpp
src/Architecture.cpp
src/CMakeLists.txt
src/cliffordsynthesis/Tableau.cpp
src/exact/ExactMapper.cpp
test/CMakeLists.txt
test/cliffordsynthesis/test_synthesis.cpp
test/test_architecture.cpp
test/test_encodings.cpp
test/test_exact.cpp
test/test_heuristic.cpp

This PR builds on https://github.com/cda-tum/dd_package/pull/125 as well as https://github.com/cda-tum/qfr/pull/246 and refactors the overall CMake configuration.
The newly enabled compiler warnings showed some alerts, which have subsequently been fixed.

♻️ Refactor CMake Configuration

---

README.md
docs/source/Publications.rst
docs/source/index.rst
docs/source/refs.bib

Signed-off-by: Lukas Burgholzer <lukas.burgholzer@jku.at>
This PR adds our latest (invited) overview paper to the documentation and the readme.

📝 Add QMAP overview paper

---

docs/source/_static/custom.css

This tiny PR improves dark-mode support in the docs a bit by making properties easier to read.
Thanks to @hillmich!

🎨 Small dark-mode docs improvement

---

.github/release-drafter.yml

Some fine tuning for the release drafter action.

🔧 Update Release Drafter Configuration

---

.gitmodules
CMakeLists.txt
MANIFEST.in
mqt/qmap/CMakeLists.txt
mqt/qmap/bindings.cpp
setup.py
src/CMakeLists.txt

This PR replaces the QFR submodule with the newly introduced MQT Core library that subsumes the QFR, DD package, and ZX package. At the moment, this entails no functional changes and only required minor adaptions.

🚚 Move to MQT Core package

---

.github/contributing.rst
.github/support.rst
LICENSE.md
README.md
docs/source/DevelopmentGuide.rst
docs/source/Installation.rst
docs/source/index.rst
pyproject.toml

This PR just fixes up a couple of things throughout the documentation regarding the move from `qmap` to `mqt-qmap` and from the `QFR` library to `MQT Core`.

📝 Prepare docs for new release

---

.pre-commit-config.yaml
pyproject.toml

This PR adds a new pre-commit check that runs Scientific Python's Repo Review and checks for the use of established best practices throughout the project.
Adding the check immediately revealed the use of a deprecated setting.

✨ add sp-repo-review to pre-commit check

---

.github/codecov.yml
.github/workflows/cd.yml
.github/workflows/ci.yml
noxfile.py

This PR updates the reusable MQT workflows to their latest version. It also makes use of explicit versioning in order to avoid surprises caused by updates in the future and to allow getting updates from dependabot.

👷⬆️ update reusable workflows

---

LICENSE.md
README.md
docs/source/conf.py

This PR improves the documentation by updating the year in the copyright, updating a link to an external documentation and making the MQT logo clickable. 
All changes are taken from the PR cda-tum/mqt-core#589.

📝 Improve and Update documentation

---

.clang-tidy
.editorconfig
.git_archival.txt
.gitignore

This PR updates a couple of the configuration files responsible for code formating, linting, etc.
This brings the project closer to the currently established best practises from mqt-core.

🎨 Code format and linting config update

---

noxfile.py
pyproject.toml

This PR updates the project to the latest scikit-build-core version that was just released and adapts the configuration correspondingly.

⬆️ update to scikit-build-core 0.10

---

pyproject.toml
src/mqt/qmap/_compat/__init__.py
src/mqt/qmap/_compat/importlib/__init__.py
src/mqt/qmap/_compat/importlib/resources.py
src/mqt/qmap/_compat/typing.py
src/mqt/qmap/subarchitectures.py
src/mqt/qmap/visualization/search_visualizer.py
src/mqt/qmap/visualization/visualize_search_graph.py
test/python/test_subarchitectures.py

This PR improves the usability of the Python typing within the project by introducing compatibility modules as in some of our other projects.

🚨🎨 improved typing usability

---

.github/workflows/upstream.yml

This PR avoid issues such as #643 from being created on cancellation events of the workflow.
Fixes #643

🩹 avoid spurious upstream failures on cancellation

---

.github/release-drafter.yml
CHANGELOG.md
UPGRADING.md
docs/CHANGELOG.md
docs/UPGRADING.md
docs/conf.py
docs/index.md

This PR adds a changelog and upgrade guide infrastructure as well as the corresponding entries for the 3.0.0 release.

📝 Add changelog and upgrade guide

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
.github/pull_request_template.md

This PR updates the issue and PR templates for the project to the latest best practices.

📝 Update Issue and PR templates

---

CHANGELOG.md

This PR fixes a couple of broken links in the project changelog.

✏️ Fix broken links in changelog

---

noxfile.py
pyproject.toml
sitecustomize.py
uv.lock

This PR speeds up the test suite. It is a copy of https://github.com/munich-quantum-toolkit/bench/pull/602.

⚡ Speed up test suite

---

CHANGELOG.md
UPGRADING.md

This PR prepares the release of v3.2.0.

🔖 Prepare release of v3.2.0

---

.github/workflows/ci.yml
CHANGELOG.md
src/na/zoned/placer/VertexMatchingPlacer.cpp

This PR fixes the bug in the c++ code that was mentioned in #704.

🐛 Fix out-of-bounds access to reuse qubits

---

.readthedocs.yaml
CHANGELOG.md
UPGRADING.md
noxfile.py

This PR changes the test setup to not rebuild MQT Core from source. 
Related to https://github.com/munich-quantum-toolkit/qcec/issues/661

🎨 Do not rebuild MQT Core in tests

---

python/mqt/qmap/clifford_synthesis.pyi
python/mqt/qmap/na/state_preparation.pyi
python/mqt/qmap/plugins/qiskit/sc/compile.py

Fix minor typos
- tehcniques -> techniques
- if give -> if given
- guarantueed -> guaranteed

Fix minor typos

---

CHANGELOG.md
UPGRADING.md

This PR prepares the release of v3.3.0.

🔖 Prepare release of v3.3.0

---

.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md
UPGRADING.md

See https://github.com/munich-quantum-toolkit/core/pull/1165/ for more information.
Fixes #753

🔥 Drop support for x86 macOS systems
